<?php

namespace ContainerCrL0E9v;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VJtuVZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.vJtuV_Z' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.vJtuV_Z'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'categoriesBdd' => ['privates', 'App\\Repository\\CategoryRepository', 'getCategoryRepositoryService', false],
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'categoriesBdd' => 'App\\Repository\\CategoryRepository',
            'manager' => '?',
        ]);
    }
}
