<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCrL0E9v\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCrL0E9v/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCrL0E9v.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCrL0E9v\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCrL0E9v\App_KernelDevDebugContainer([
    'container.build_hash' => 'CrL0E9v',
    'container.build_id' => 'ad0ab30c',
    'container.build_time' => 1606749140,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCrL0E9v');
